version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  flask:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
